# Generated by Django 4.2.3 on 2024-04-04 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=50)),
                ('locale', models.CharField(max_length=50)),
                ('primary_exchange', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('currency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_updated', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_home.ticker')),
            ],
        ),
    ]
