# Generated by Django 4.2.3 on 2024-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='cik',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
