# Generated by Django 4.2.3 on 2024-04-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0002_ticker_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='composite_figi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='last_updated_utc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='share_class_figi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
