# Generated by Django 4.2.3 on 2024-04-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0003_ticker_composite_figi_ticker_last_updated_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='homepage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='list_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='logo_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='round_lot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='share_class_shares_outstanding',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sic_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sic_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ticker_root',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='weighted_shares_outstanding',
            field=models.BigIntegerField(null=True),
        ),
    ]
