# Generated by Django 4.2.3 on 2024-04-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0004_asset_address1_asset_city_asset_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.AlterField(
            model_name='asset',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='homepage_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='icon_url',
            field=models.URLField(null=True),
        ),
    ]
