# Generated by Django 4.2.3 on 2024-04-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0005_remove_asset_price_alter_asset_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='primary_exchange',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
