# Generated by Django 4.2.3 on 2024-04-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0006_alter_ticker_primary_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='cik',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
