# Generated by Django 4.2.3 on 2024-04-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_home', '0008_alter_ticker_primary_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='address1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sic_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='composite_figi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='share_class_figi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
